#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_service() {
		stop_service
		procd_open_instance
		procd_set_param command minieap
		procd_set_param file /etc/minieap.conf
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_set_param respawn 0
		procd_close_instance
		echo "MiniEAP 已启动"
}

stop_service() {
	if [ -e "/var/run/minieap.pid" ]; then
		killall minieap
		echo "MiniEAP 已经接受退出指令"
		rm -r /var/run/minieap.pid
		echo "已发送删除PID文件请求"
	else
		echo "MiniEAP 没有被运行"
	fi
}

reload_service() {
	restart
}